from cal.simpson import simpson13, fx

#print("==---------------------------------------------------------------==\n||                                                               ||\n||  F A C U L T A D  D E  E S T U D I O S  S U P E R I O R E S   ||\n||                          A R A G Ó N                          ||\n||    -------------------------------------------------------    ||\n||     P R O B A B I L I D A D   Y   E S T A D I S T I C A       ||\n||    -------------------------------------------------------    ||\n||           P R O F:  G E R A R D O   G O N Z A L E Z           ||\n||                      H E R N A N D E Z                        ||\n||    -------------------------------------------------------    ||\n||                     G R U P O:  2 4 5 8                       ||\n||    -------------------------------------------------------    ||\n||                S E M E S T R E:  2 0 1 9 - 1                  ||\n||    -------------------------------------------------------    ||\n||                   I N T E G R A N T E S:                      ||\n||                                                               ||\n||                                                               ||\n||         - Argüello Argüello Cristian                          ||\n||         - Bernal Santillan Marco Antonio                      ||\n||         - Martinez Gonzalez Junior Christian                  ||\n||         - Rojas Solano Manuel Alejandro                       ||\n||                                                               ||\n||                                                               ||\n||                                                               ||\n||===============================================================||\n\n")

print("╔═══════════════════════════════════════════════════════════════╗\n║                                                               ║\n║  F A C U L T A D  D E  E S T U D I O S  S U P E R I O R E S   ║\n║                          A R A G Ó N                          ║\n║    ───────────────────────────────────────────────────────    ║\n║     P R O B A B I L I D A D   Y   E S T A D I S T I C A       ║\n║    ───────────────────────────────────────────────────────    ║\n║           P R O F:  G E R A R D O   G O N Z A L E Z           ║\n║                      H E R N A N D E Z                        ║\n║    ───────────────────────────────────────────────────────    ║\n║                     G R U P O:  2 4 5 8                       ║\n║    ───────────────────────────────────────────────────────    ║\n║                S E M E S T R E:  2 0 1 9 - 1                  ║\n║    ───────────────────────────────────────────────────────    ║\n║                   I N T E G R A N T E S:                      ║\n║                                                               ║\n║                                                               ║\n║         - Argüello Argüello Cristian                          ║\n║         - Bernal Santillan Marco Antonio                      ║\n║         - Martinez Gonzalez Junior Christian                  ║\n║         - Rojas Solano Manuel Alejandro                       ║\n║                                                               ║\n║                                                               ║\n╚═══════════════════════════════════════════════════════════════╝\n")

n = int(input("Inserta el número de iteraciones: "))
a = float(input("Inserta intervalo inferior: "))
b = float(input("Inserta intervalo superior: "))
f = str(input("Inserta la función: "))

print("\nEl resultado de la integral es: ")
print(simpson13(n, a, b, f))
